import 'package:flutter/material.dart';

/// The three inks of the Otaku Reader mark, and the black it sits on.
///
/// These are **measured**, not picked by eye: the artwork was quantised and the
/// modal colour of each hue family taken, so what the app renders is the ink the
/// logo is actually printed in rather than something that looks about right next
/// to it. `tool/generate_launcher_icons.py` reads the same artwork for the
/// launcher icon, so the icon and the UI cannot drift apart.
abstract final class BrandPalette {
  /// The petals. 94% saturation, and the colour the mark is recognised by.
  static const Color petal = Color(0xFFFA60BE);

  /// The wordmark and the kanji strokes.
  static const Color ink = Color(0xFF313575);

  /// The accents between the petals.
  static const Color blossom = Color(0xFFE17559);

  /// The ground the mark is drawn on. Used by the launcher icon and the launch
  /// window, not by the app's own surfaces — those come from the M3 engine, so
  /// they follow the user's light/dark choice and the OLED switch.
  static const Color ground = Color(0xFF0A0A0B);
}

/// The tonal algorithm the app defaults to.
///
/// Flutter's own default, `tonalSpot`, caps chroma hard: it renders the petal
/// pink as `#874B6C`, a muted mauve that nothing in the logo is printed in.
/// `fidelity` is the variant built to keep a seed recognisable, and it gives
/// `#AD1B7E` / `#1A1E5E` / `#9D422A` — the mark's own three inks, in light mode.
/// Every variant stays selectable; this only decides where a fresh install
/// starts.
///
/// Named through the enum rather than stored as the literal `1`. This repo has
/// already shipped `int status = 5` meaning something nobody intended, and an
/// index default is the same shape of mistake.
const DynamicSchemeVariant kDefaultSchemeVariant =
    DynamicSchemeVariant.fidelity;

/// Builds a scheme whose three accent families come from the three inks.
///
/// `ColorScheme.fromSeed` takes one seed, and its `secondary`/`tertiary`
/// overrides replace the **finished role colours** rather than the palettes
/// behind them — so handing it a navy `secondary` would leave `onSecondary`
/// derived from the pink, and the pairing is then unreadable by construction.
///
/// Instead each ink seeds its own scheme at the same brightness, variant and
/// contrast, and its `primary` family is lifted whole into the slot it belongs
/// in. Every on-colour was generated by Flutter's own engine *against the colour
/// it sits on*, so contrast is guaranteed rather than hoped for, and the app
/// keeps tracking whatever that engine does in future versions.
ColorScheme brandColorScheme({
  required Brightness brightness,
  required DynamicSchemeVariant variant,
}) {
  ColorScheme familyOf(Color seed) => ColorScheme.fromSeed(
    seedColor: seed,
    brightness: brightness,
    dynamicSchemeVariant: variant,
  );

  final petal = familyOf(BrandPalette.petal);
  final ink = familyOf(BrandPalette.ink);
  final blossom = familyOf(BrandPalette.blossom);

  return petal.copyWith(
    secondary: ink.primary,
    onSecondary: ink.onPrimary,
    secondaryContainer: ink.primaryContainer,
    onSecondaryContainer: ink.onPrimaryContainer,
    secondaryFixed: ink.primaryFixed,
    secondaryFixedDim: ink.primaryFixedDim,
    onSecondaryFixed: ink.onPrimaryFixed,
    onSecondaryFixedVariant: ink.onPrimaryFixedVariant,
    tertiary: blossom.primary,
    onTertiary: blossom.onPrimary,
    tertiaryContainer: blossom.primaryContainer,
    onTertiaryContainer: blossom.onPrimaryContainer,
    tertiaryFixed: blossom.primaryFixed,
    tertiaryFixedDim: blossom.primaryFixedDim,
    onTertiaryFixed: blossom.onPrimaryFixed,
    onTertiaryFixedVariant: blossom.onPrimaryFixedVariant,
  );
}
